WHITES = 'player_1'
BLACKS = 'player_2'
W_PAWN = 'p'
B_PAWN = 'P'
W_ROOK = 'w'
B_ROOK = 'W'
W_KNIGHT = 's'
B_KNIGHT = 'S'
W_BISHOP = 'g'
B_BISHOP = 'G'
W_QUEEN = 'h'
B_QUEEN = 'H'
W_KING = 'k'
B_KING = 'K'
EMPTY = '-'
FIGURES = {
    WHITES: [W_PAWN, W_ROCK, W_KNIGHT, W_BISHOP, W_QUEEN, W_KING],
    BLACKS: [B_PAWN, B_ROCK, B_KNIGHT, B_BISHOP, B_QUEEN, B_KING]
}
ENEMY_FIGURES = {
    BLACKS: [W_PAWN, W_ROCK, W_KNIGHT, W_BISHOP, W_QUEEN, W_KING],
    WHITES: [B_PAWN, B_ROCK, B_KNIGHT, B_BISHOP, B_QUEEN, B_KING]
}
BOARD_SET = [
    [W_ROCK, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_ROCK],
    [W_KNIGHT, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_KNIGHT],
    [W_BISHOP, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_BISHOP],
    [W_QUEEN, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_KING],
    [W_KING, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_QUEEN],
    [W_BISHOP, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_BISHOP],
    [W_KNIGHT, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_KNIGHT],
    [W_ROCK, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_ROCK]
]
# test = [
#     [W_ROCK, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_ROCK],
#     [W_KNIGHT, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_KNIGHT],
#     [W_BISHOP, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_BISHOP],
#     [W_QUEEN, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_KING],
#     [W_KING, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_QUEEN],
#     [W_BISHOP, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_BISHOP],
#     [W_KNIGHT, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_KNIGHT],
#     [W_ROCK, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_ROCK]
# ]





