WHITES = 'white'
BLACKS = 'black'
W_PAWN = 'white_pawn'
B_PAWN = 'black_pawn'
W_ROOK = 'white_rook'
B_ROOK = 'black_rook'
W_KNIGHT = 'white_knight'
B_KNIGHT = 'black_knight'
W_BISHOP = 'white_bishop'
B_BISHOP = 'black_bishop'
W_QUEEN = 'white_queen'
B_QUEEN = 'black_queen'
W_KING = 'white_king'
B_KING = 'black_king'
EMPTY = '-'
FIGURES = {
    WHITES: [W_PAWN, W_ROOK, W_KNIGHT, W_BISHOP, W_QUEEN, W_KING],
    BLACKS: [B_PAWN, B_ROOK, B_KNIGHT, B_BISHOP, B_QUEEN, B_KING]
}
ENEMY_FIGURES = {
    BLACKS: [W_PAWN, W_ROOK, W_KNIGHT, W_BISHOP, W_QUEEN, W_KING],
    WHITES: [B_PAWN, B_ROOK, B_KNIGHT, B_BISHOP, B_QUEEN, B_KING]
}
BOARD_SET = [
    [W_ROOK, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_ROOK],
    [W_KNIGHT, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_KNIGHT],
    [W_BISHOP, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_BISHOP],
    [W_QUEEN, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_KING],
    [W_KING, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_QUEEN],
    [W_BISHOP, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_BISHOP],
    [W_KNIGHT, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_KNIGHT],
    [W_ROOK, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_ROOK]
]
# test = [
#     [W_ROOK, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_ROOK],
#     [W_KNIGHT, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_KNIGHT],
#     [W_BISHOP, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_BISHOP],
#     [W_QUEEN, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_KING],
#     [W_KING, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_QUEEN],
#     [W_BISHOP, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_BISHOP],
#     [W_KNIGHT, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_KNIGHT],
#     [W_ROOK, W_PAWN, EMPTY, EMPTY, EMPTY, EMPTY, B_PAWN, B_ROOK]
# ]





